specVersion: 1.0.0
name: pns
version: 0.1.2
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '>=1.0.0'
repository: 'https://github.com/pnsproject/pnsquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  endpoint: 'wss://moonbeam.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbeam-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 895458
    processor:
      file: ./dist/moonbeamEvm.js
      options:
        abi: controller
        address: '0x268C915680Da0b74D2EE520866716a7a295fEdf6'
    assets:
      controller:
        file: ./controller.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCapacityUpdated
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - CapacityUpdated(uint256 tokenId, uint256 capacity)
        - handler: handleControllerConfigUpdated
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ConfigUpdated(uint256 flags)
        - handler: handleMetadataUpdated
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - MetadataUpdated(uint256[] data)
        - handler: handleNameRegistered
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - NameRegistered(address to,uint256 node,uint256 cost,uint256 expires,string name)
        - handler: handleNameRenewed
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - NameRenewed(uint256 node,uint256 cost,uint256 expires,string name)
        - handler: handlePriceChanged
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - PriceChanged(uint256[] basePrices, uint256[] rentPrices)
        - handler: handleNameRedeem
          kind: substrate/MoonbeamCall
          filter:
            function: nameRedeem(string name,address owner,uint256 duration,uint256 deadline,bytes code)
        - handler: handleNameRegister
          kind: substrate/MoonbeamCall
          filter:
            function: nameRegister(string name,address owner,uint256 duration)
        - handler: handleRenew
          kind: substrate/MoonbeamCall
          filter:
            function: renew(string name,uint256 duration)
        - handler: handleNameRegisterByManager
          kind: substrate/MoonbeamCall
          filter:
            function: nameRegisterByManager(string,address,uint256,uint256[],string[])
        - handler: handleNameRegisterWithConfig
          kind: substrate/MoonbeamCall
          filter:
            function: nameRegisterWithConfig(string,address,uint256,uint256[],string[])
        - handler: handleRenewByManager
          kind: substrate/MoonbeamCall
          filter:
            function: renewByManager(string name,uint256 duration)
  - kind: substrate/Moonbeam
    startBlock: 895456
    processor:
      file: ./dist/moonbeamEvm.js
      options:
        abi: pns
        address: '0x7d5F0398549C9fDEa03BbDde388361827cb376D5'
    assets:
      pns:
        file: ./pns.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewSubdomain
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - NewSubdomain(address to,uint256 tokenId,uint256 subtokenId,string name)
        - handler: handleTransfer
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 indexed tokenId)
        - handler: handleApproval
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Approval(address indexed owner,address indexed approved,uint256 indexed tokenId)
        - handler: handleApprovalForAll
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ApprovalForAll(address indexed owner,address indexed operator,bool approved)
        - handler: handleNewResolver
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - NewResolver(uint256 tokenId,address resolver)
        - handler: handleNewKey
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - NewKey(string indexed keyIndex,string key)        
        - handler: handleResetRecords
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ResetRecords(uint256 indexed keyIndex)   
        - handler: handleSet
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ResetRecords(uint256 indexed tokenId,uint256 indexed keyHash,string value)
        - handler: handleSetName
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - SetName(address indexed addr,uint256 indexed tokenId)  
        - handler: handleSetNftName
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - SetNftName(address indexed nftAddr,uint256 indexed nftTokenId,uint256 indexed tokenId)
        - handler: handlePnsConfigUpdated
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ConfigUpdated(uint256 flags)
        - handler: handleManagerChanged
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ManagerChanged(address indexed manager,bool indexed role)
        - handler: handleRootOwnershipTransferred
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - RootOwnershipTransferred(address indexed oldRoot,address indexed newRoot)
